"use client";

import React, { useMemo, useState } from "react";
import { rounds } from "@/lib/data";
import { saveSubmission, type AiReviewAnswer } from "@/lib/storage";
import { Card, Pill, PrimaryButton, TextArea, TextInput } from "@/components/ui";

type FirstChoice = "A" | "B";
type SecondChoice = "기존 유지" | "일부 수정" | "판단 변경";
type ReviewChoice = "O" | "X" | "모르겠음";
type Tone = "blue" | "teal" | "purple" | "orange" | "green" | "gray";

const reviewItems = ["우리 조직의 맥락이 반영되었는가?", "팀원의 감정과 체면을 고려했는가?", "상사와 타부서의 기대를 놓치지 않았는가?", "실행 비용을 과소평가하지 않았는가?", "실제 팀장이 말할 수 있는 문장인가?"];
const secondOptions: { value: SecondChoice; title: string; desc: string; tone: "blue" | "teal" | "purple"; icon: string }[] = [
  { value: "기존 유지", title: "처음 판단의 방향을 유지", desc: "돌발상황을 보아도 1차 판단의 큰 방향은 그대로 둡니다.", tone: "blue", icon: "🛡️" },
  { value: "일부 수정", title: "방향은 유지하되 조건을 조정", desc: "핵심 방향은 살리되 범위·순서·설명 방식을 수정합니다.", tone: "teal", icon: "🔧" },
  { value: "판단 변경", title: "처음 판단과 다른 방향 선택", desc: "새로운 변수가 결정적으로 커져 판단 방향을 바꿉니다.", tone: "purple", icon: "↗️" },
];
const secondQuestions: Record<SecondChoice, string[]> = {
  "기존 유지": ["돌발상황을 보았음에도 기존 판단을 유지해도 된다고 보는 가장 강한 근거는 무엇입니까?", "기존 판단을 유지할 때 가장 커지는 위험은 무엇이며, 어떻게 통제하겠습니까?", "기존 판단을 유지한다는 결정을 누구에게, 어떤 첫 문장으로 설명하겠습니까?"],
  "일부 수정": ["무엇은 그대로 유지하고, 무엇은 수정해야 합니까?", "일부 수정으로 새롭게 생기는 비용이나 부담은 무엇입니까?", "수정안을 실행하기 위해 누구와 언제 무엇을 다시 합의해야 합니까?"],
  "판단 변경": ["1차 판단을 바꿔야 한다고 보게 만든 결정적 증거는 무엇입니까?", "판단을 바꿀 때 생기는 신뢰, 설명, 일정상의 비용은 무엇입니까?", "판단 변경을 팀원이나 상사에게 어떻게 설명해야 저항을 줄일 수 있습니까?"],
};
const finalGuides = [
  ["나는 이 상황을", "예시: 나는 이 상황을 단순 일정 문제가 아니라 우선순위와 자원 배분의 문제로 본다."],
  ["나의 최종 선택은", "예시: 나의 최종 선택은 기존 일정을 유지하되 품질 점검 조건을 추가하는 일부 수정안이다."],
  ["이 선택의 가장 큰 비용은", "예시: 일부 팀원의 단기 부담과 상사에게 추가 설명해야 한다는 점이다."],
  ["그래서 붙일 실행 조건은", "예시: 오늘 안에 핵심 업무 범위와 품질 기준을 다시 합의하겠다."],
  ["내일 바로 할 첫 행동은", "예시: 내일 오전 핵심 담당자와 15분 점검 미팅을 열겠다."],
];
const toneMap: Record<Tone, string> = { blue: "bg-blue-50 text-blue-700", teal: "bg-teal-50 text-teal-700", purple: "bg-violet-50 text-violet-700", orange: "bg-orange-50 text-orange-700", green: "bg-emerald-50 text-emerald-700", gray: "bg-slate-50 text-slate-600" };

function RequiredMessage({ children }: { children: React.ReactNode }) { return <p className="rounded-2xl bg-orange-50 px-4 py-3 text-center text-xs font-bold leading-5 text-orange-600">{children}</p>; }
function Shell({ children, step }: { children: React.ReactNode; step: number }) { const labels = ["홈", "상황", "1차", "돌발", "2차", "AI", "결정"]; return <div className="mx-auto flex min-h-[860px] w-full max-w-[430px] flex-col overflow-hidden rounded-[2.4rem] border border-slate-200 bg-slate-50 shadow-2xl"><div className="bg-white/95 px-5 pb-2 pt-5 backdrop-blur"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-slate-500">9:41</span><b className="text-sm text-slate-800">업무관리 Decision Journey</b><span className="relative h-8 w-8 rounded-full bg-gradient-to-br from-blue-100 to-teal-100"><span className="absolute -right-1 -top-1 flex h-4 w-4 items-center justify-center rounded-full bg-red-500 text-[10px] font-bold text-white">2</span></span></div><div className="mt-3 flex justify-center gap-2">{labels.map((_, i) => <span key={i} className={`h-2.5 w-2.5 rounded-full ${i <= step ? "bg-blue-600" : "bg-slate-200"}`} />)}</div></div><div className="flex-1 overflow-y-auto px-5 py-5">{children}</div><div className="grid grid-cols-5 gap-1 border-t border-slate-100 bg-white px-3 py-3 text-center text-[10px] text-slate-400">{["홈", "라운드", "로그북", "코칭", "내 정보"].map((s, i) => <div key={s} className={i === 0 ? "font-bold text-blue-600" : ""}>●<br />{s}</div>)}</div></div>; }
function Nav({ screen, nextDisabled, onPrev, onHome, onNext, label = "다음" }: { screen: number; nextDisabled: boolean; onPrev: () => void; onHome: () => void; onNext: () => void; label?: string }) { if (screen < 3 || screen > 15) return null; return <div className="mb-5 grid grid-cols-3 gap-2 rounded-3xl border border-slate-100 bg-white p-2 shadow-sm"><button onClick={onPrev} disabled={screen === 3} className="rounded-2xl bg-slate-100 px-3 py-3 text-sm font-extrabold text-slate-600 disabled:text-slate-300">← 이전</button><button onClick={onHome} className="rounded-2xl bg-blue-50 px-3 py-3 text-sm font-extrabold text-blue-700">홈</button><button onClick={onNext} disabled={nextDisabled} className="rounded-2xl bg-blue-600 px-3 py-3 text-sm font-extrabold text-white disabled:bg-slate-100 disabled:text-slate-300">{label} →</button></div>; }
function Info({ title, children, tone = "blue" }: { title: string; children: React.ReactNode; tone?: Tone }) { return <Card className="p-4"><span className={`mb-3 inline-flex rounded-full px-3 py-1 text-xs font-extrabold ${toneMap[tone]}`}>{title}</span><div className="text-sm leading-7 text-slate-600">{children}</div></Card>; }

function ImageHero({ compact = false }: { compact?: boolean }) {
  return <div className={`relative mt-5 overflow-hidden rounded-[2rem] shadow-inner ${compact ? "h-44" : "h-52"}`}><div className="absolute inset-0 bg-cover bg-center" style={{ backgroundImage: "url('/lighthouse-hero.png')" }} /><div className="absolute inset-0 bg-gradient-to-r from-white/88 via-white/45 to-blue-50/10" /><div className="absolute inset-x-0 bottom-0 h-20 bg-gradient-to-t from-white/85 to-transparent" /><div className="absolute left-5 top-5 rounded-full bg-white/85 px-3 py-1 text-xs font-bold text-blue-700 shadow-sm">판단 여정</div><div className="absolute left-5 top-14 max-w-[190px] rounded-2xl bg-white/80 px-4 py-3 text-sm font-extrabold leading-6 text-slate-700 shadow-sm">선택의 길을 따라<br />판단 기준을 세웁니다</div></div>;
}
function ProgressRing() { return <div className="flex h-28 w-28 items-center justify-center rounded-full bg-gradient-to-br from-blue-600 via-blue-500 to-violet-500 p-2 shadow-lg shadow-blue-100"><div className="flex h-full w-full flex-col items-center justify-center rounded-full bg-white"><b className="text-3xl text-slate-900">78%</b><span className="text-xs font-bold text-slate-500">여정 완료</span></div></div>; }
function RoundMiniCard({ title, index, active, done, onClick }: { title: string; index: number; active?: boolean; done?: boolean; onClick: () => void }) { const icon = ["📋", "👥", "💻", "☕"][index % 4]; return <button onClick={onClick} className={`min-h-[158px] rounded-3xl border p-4 text-left shadow-sm transition ${active ? "border-blue-400 bg-blue-50 ring-4 ring-blue-100" : "border-slate-100 bg-white"}`}><div className="flex items-start justify-between"><Pill tone={done ? "teal" : active ? "blue" : "gray"}>라운드 {index + 1}</Pill><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-slate-50 text-2xl shadow-inner">{icon}</span></div><p className="mt-4 min-h-[42px] text-sm font-black leading-6 text-slate-800">{title}</p><div className="mt-3 flex items-center gap-1">{[0, 1, 2, 3, 4].map((i) => <span key={i} className={`h-2.5 w-2.5 rounded-full ${done || (active && i < 2) ? "bg-blue-600" : "bg-slate-200"}`} />)}</div><p className="mt-3 text-xs font-bold text-slate-500">{done ? "완료" : active ? "진행 중" : "대기"}</p></button>; }
function StepHero({ badge, title, subtitle, icon, tone = "blue" }: { badge: string; title: string; subtitle: string; icon: string; tone?: Tone }) { return <div className="rounded-[2rem] bg-gradient-to-br from-white via-blue-50/60 to-teal-50 p-5 shadow-sm"><div className="flex items-center justify-between"><Pill tone={tone}>{badge}</Pill><span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-white text-3xl shadow-inner">{icon}</span></div><h2 className="mt-4 text-2xl font-black leading-tight text-slate-900">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{subtitle}</p></div>; }
function FirstOptionCard({ label, title, selected, onClick, tone }: { label: FirstChoice; title: string; selected: boolean; onClick: () => void; tone: "blue" | "teal" }) { const selectedClass = tone === "blue" ? "border-blue-400 bg-blue-50 ring-blue-100" : "border-teal-400 bg-teal-50 ring-teal-100"; const badge = tone === "blue" ? "bg-blue-600" : "bg-teal-600"; return <button onClick={onClick} className={`w-full rounded-3xl border p-4 text-left transition ${selected ? `${selectedClass} ring-4` : "border-slate-200 bg-white"}`}><div className="flex gap-3"><div className={`flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl text-lg font-black text-white ${badge}`}>{label}</div><div className="flex-1"><div className="text-sm font-bold text-slate-400">1차 선택안</div><p className="mt-1 text-base font-extrabold leading-6 text-slate-800">{title}</p></div><div className={`mt-1 h-5 w-5 rounded-full border-2 ${selected ? "border-blue-600 bg-blue-600" : "border-slate-300"}`} /></div></button>; }
function SecondDecisionCard({ option, selected, onClick }: { option: { value: SecondChoice; title: string; desc: string; tone: "blue" | "teal" | "purple"; icon: string }; selected: boolean; onClick: () => void }) { const selectedClass = option.tone === "blue" ? "border-blue-400 bg-blue-50 ring-blue-100" : option.tone === "teal" ? "border-teal-400 bg-teal-50 ring-teal-100" : "border-violet-400 bg-violet-50 ring-violet-100"; const badge = option.tone === "blue" ? "bg-blue-600" : option.tone === "teal" ? "bg-teal-600" : "bg-violet-600"; return <button onClick={onClick} className={`w-full rounded-3xl border p-4 text-left transition ${selected ? `${selectedClass} ring-4` : "border-slate-200 bg-white"}`}><div className="flex items-center gap-3"><div className={`flex min-h-12 w-20 shrink-0 items-center justify-center rounded-2xl px-2 text-center text-sm font-extrabold leading-5 text-white ${badge}`}>{option.value}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span>{option.icon}</span><div className="text-base font-extrabold leading-6 text-slate-800">{option.title}</div></div><div className="mt-1 text-sm leading-6 text-slate-500">{option.desc}</div></div><div className={`h-5 w-5 shrink-0 rounded-full border-2 ${selected ? "border-blue-600 bg-blue-600" : "border-slate-300"}`} /></div></button>; }
function SurpriseVisual({ n }: { n: number }) { const icons = ["👤", "⚠️", "📈"]; return <div className="rounded-[2rem] bg-gradient-to-br from-slate-900 via-blue-950 to-teal-900 p-5 text-white shadow-lg"><div className="flex items-center justify-between"><span className="rounded-full bg-white/10 px-4 py-1 text-xs font-bold">돌발상황 {n}</span><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/10 text-2xl">{icons[n - 1]}</span></div><h2 className="mt-5 text-2xl font-black leading-tight">새 변수가<br />발생했습니다</h2><p className="mt-2 text-sm text-white/70">처음 판단의 숨은 비용을 다시 확인해보세요.</p></div>; }

export default function LearnerAppV12() {
  const [screen, setScreen] = useState(0); const [code, setCode] = useState(""); const [team, setTeam] = useState(""); const [roundIndex, setRoundIndex] = useState(1); const [firstChoice, setFirstChoice] = useState<FirstChoice | null>(null); const [firstReason, setFirstReason] = useState(""); const [concern, setConcern] = useState(""); const [secondChoice, setSecondChoice] = useState<SecondChoice | null>(null); const [secondAnswers, setSecondAnswers] = useState(["", "", ""]); const [aiSummary, setAiSummary] = useState(""); const [copied, setCopied] = useState(false); const [reviewAnswers, setReviewAnswers] = useState<(ReviewChoice | "")[]>(reviewItems.map(() => "")); const [reviewNote, setReviewNote] = useState(""); const [finalLines, setFinalLines] = useState(["", "", "", "", ""]);
  const round = rounds[roundIndex]; const filled = (v: string) => v.trim().length > 0; const participantName = team.trim() || "참여자"; const firstChoiceText = firstChoice === "A" ? round.optionA : firstChoice === "B" ? round.optionB : "아직 선택하지 않았습니다."; const selectedQuestions = secondChoice ? secondQuestions[secondChoice] : []; const secondReason = selectedQuestions.map((q, i) => `${i + 1}. ${q}\n- ${secondAnswers[i] || ""}`).join("\n"); const canEnter = filled(code) && filled(team); const canFirst = Boolean(firstChoice) && filled(firstReason) && filled(concern); const canSecond = Boolean(secondChoice); const canSecondQuestions = Boolean(secondChoice) && secondAnswers.every(filled); const canAi = filled(aiSummary); const needReviewNote = reviewAnswers.some((a) => a === "X" || a === "모르겠음"); const canReview = reviewAnswers.every(Boolean) && (!needReviewNote || filled(reviewNote)); const canFinal = finalLines.every(filled); const finalPreview = finalLines.filter(filled).join("\n");
  const prompt = useMemo(() => `나는 팀장 역할로 업무관리 딜레마 상황을 판단하고 있습니다.\n\n[상황]\n${round.story}\n\n[나의 1차 판단]\n${firstChoice || "A/B 중 선택"}. ${firstChoiceText}\n\n[1차 판단 이유]\n${firstReason || "작성한 선택 이유"}\n\n[우려한 점]\n${concern || "작성한 우려 사항"}\n\n[돌발상황]\n1. ${round.surprises[0]}\n2. ${round.surprises[1]}\n3. ${round.surprises[2]}\n\n[나의 2차 판단]\n${secondChoice || "기존 유지/일부 수정/판단 변경 중 선택"}\n\n[2차 판단 질문 답변]\n${secondReason || "선택별 질문 답변"}\n\n[요청]\n1. 이 판단의 강점과 약점을 구분해 주세요.\n2. 제가 놓친 이해관계자 관점이 있다면 알려주세요.\n3. 기존 유지/일부 수정/판단 변경 중 현재 상황에서 어떤 선택이 더 타당한지 조건부로 비교해 주세요.\n4. 이 선택을 팀원 또는 상사에게 설명할 첫 문장 3개를 제안해 주세요.\n5. 정답처럼 말하지 말고 각 선택의 비용과 실행 조건을 함께 제시해 주세요.`, [round, firstChoice, firstChoiceText, firstReason, concern, secondChoice, secondReason]);
  const kim = `김박사의 피드백\n\n이번 선택에서 중요한 것은 무엇을 골랐는가보다 그 선택의 비용을 얼마나 알고 있었는가입니다. 당신은 1차로 ${firstChoice || "A/B"}를 선택했고, 돌발상황 이후 ${secondChoice || "2차 판단"}을 선택했습니다.\n\n좋은 판단은 경험에서 나오고, 탁월한 판단은 성찰에서 나옵니다.`;
  const reset = () => { setFirstChoice(null); setFirstReason(""); setConcern(""); setSecondChoice(null); setSecondAnswers(["", "", ""]); setAiSummary(""); setCopied(false); setReviewAnswers(reviewItems.map(() => "")); setReviewNote(""); setFinalLines(["", "", "", "", ""]); }; const startRound = (i: number) => { setRoundIndex(i); reset(); setScreen(3); }; const next = () => setScreen((s) => Math.min(s + 1, 16)); const prev = () => setScreen((s) => Math.max(s - 1, 2)); const home = () => setScreen(1); const save = () => { if (!firstChoice || !secondChoice || !canFinal) return; saveSubmission({ id: `${code}-${team}-${round.id}`, sessionCode: code.trim(), teamName: team.trim(), roundId: round.id, roundTitle: round.title, firstChoice, firstReason: firstReason.trim(), concern: concern.trim(), secondChoice, secondReason, secondQuestionAnswers: selectedQuestions.map((question, i) => ({ question, answer: secondAnswers[i].trim() })), aiQuestion: prompt, generatedPrompt: prompt, aiAnswerSummary: aiSummary.trim(), aiFeedbackSummary: aiSummary.trim(), aiReviewResults: reviewItems.map((question, i) => ({ question, answer: (reviewAnswers[i] || "모르겠음") as AiReviewAnswer })), aiReviewNote: reviewNote.trim(), finalLines: finalLines.map((x) => x.trim()), aftermath: round.aftermath, doctorKimFeedback: kim, createdAt: new Date().toISOString() }); next(); };
  const nextDisabled = screen === 4 ? !canFirst : screen === 8 ? !canSecond : screen === 9 ? !canSecondQuestions : screen === 10 ? !canAi : screen === 12 ? !canReview : screen === 13 ? !canFinal : false; const navNext = () => { if (nextDisabled) return; if (screen === 13) return save(); next(); }; const navLabel = screen === 13 ? "저장" : screen === 15 ? "요약" : "다음"; const step = screen < 2 ? 0 : screen < 4 ? 1 : screen === 4 ? 2 : screen < 8 ? 3 : screen < 10 ? 4 : screen < 13 ? 5 : 6;
  return <Shell step={step}><Nav screen={screen} nextDisabled={nextDisabled} onPrev={prev} onHome={home} onNext={navNext} label={navLabel} />
    {screen === 0 && <div className="space-y-6"><div className="rounded-[2rem] bg-gradient-to-br from-blue-50 via-white to-teal-50 p-6"><div className="text-lg font-extrabold text-blue-600">업무관리</div><h1 className="mt-2 text-4xl font-black leading-tight text-slate-900">Decision<br />Journey</h1><p className="mt-4 text-sm leading-7 text-slate-500">실제 업무 딜레마를 따라 판단을 확장해보세요.</p><ImageHero /></div><Card className="space-y-4 p-5"><TextInput label="세션 코드" placeholder="예) ABC123" value={code} onChange={setCode} /><TextInput label="팀명 / 이름" placeholder="예) 새벽등대팀 / 홍길동" value={team} onChange={setTeam} />{!canEnter && <RequiredMessage>세션 코드와 팀명/이름을 모두 입력해주세요.</RequiredMessage>}<PrimaryButton onClick={() => canEnter && setScreen(1)} disabled={!canEnter}>대시보드로 이동</PrimaryButton></Card></div>}
    {screen === 1 && <div className="space-y-5"><div className="rounded-[2rem] bg-gradient-to-br from-blue-50 via-white to-teal-50 p-5"><div className="text-sm font-extrabold text-blue-600">업무관리</div><h2 className="mt-1 text-3xl font-black leading-tight text-slate-900">{participantName} 님,<br />오늘의 판단 여정을<br />시작해볼까요?</h2><p className="mt-3 text-sm text-slate-500">🔥 꾸준함이 리더십을 만듭니다.</p><ImageHero compact /></div><Card className="p-5"><div className="grid grid-cols-[120px_1fr] gap-4"><ProgressRing /><div><Pill>진행 중 라운드</Pill><h3 className="mt-3 text-lg font-black text-slate-900">라운드 {round.id} · {round.title}</h3><div className="mt-3 flex items-center gap-2">{[0,1,2,3,4].map((i)=><span key={i} className={`flex h-7 w-7 items-center justify-center rounded-full text-xs font-bold ${i<2?"bg-blue-600 text-white":"bg-slate-100 text-slate-400"}`}>{i<2?"✓":i+1}</span>)}</div><button onClick={() => startRound(roundIndex)} className="mt-4 w-full rounded-2xl bg-blue-600 px-4 py-3 text-sm font-extrabold text-white">라운드 시작하기 →</button></div></div></Card><div><div className="mb-3 flex items-center justify-between"><b className="text-slate-900">라운드 선택</b><span className="text-sm font-bold text-blue-600">1~4라운드</span></div><div className="grid grid-cols-2 gap-3">{rounds.slice(0,4).map((r,i)=><RoundMiniCard key={r.id} title={r.title} index={i} active={i===roundIndex} done={i===0} onClick={()=>startRound(i)} />)}</div></div><div className="rounded-3xl bg-slate-900 p-5 text-white"><div className="flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-white/10 text-3xl">👨‍🏫</div><div><b>김박사의 한마디</b><p className="mt-2 text-sm leading-6 text-slate-200">좋은 판단은 경험에서 나오고, 탁월한 판단은 성찰에서 나옵니다.</p></div></div></div></div>}
    {screen === 2 && <div className="space-y-5"><Pill>라운드 선택</Pill><h2 className="text-2xl font-black text-slate-900">업무관리 딜레마</h2>{rounds.map((r, i) => <button key={r.id} onClick={() => startRound(i)} className="w-full rounded-3xl border border-slate-100 bg-white p-4 text-left shadow-sm"><Pill tone={i % 3 === 0 ? "blue" : i % 3 === 1 ? "teal" : "purple"}>라운드 {r.id}</Pill><h3 className="mt-3 text-lg font-extrabold text-slate-800">{r.title}</h3><p className="mt-1 text-sm text-slate-500">{r.subtitle}</p></button>)}</div>}
    {screen === 3 && <div className="space-y-5"><StepHero badge={`라운드 ${round.id}`} title="상황 카드" subtitle="먼저 현장의 장면과 핵심 질문을 차분히 읽어보세요." icon="🧭" tone="blue"/><Card className="p-5"><div className="mb-3 flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-50 text-2xl">📌</span><h3 className="text-lg font-extrabold text-slate-800">{round.title}</h3></div><p className="text-sm leading-7 text-slate-600">{round.story}</p></Card><Card className="bg-blue-50/70 p-5 text-center"><b className="text-blue-700">핵심 질문</b><p className="mt-2 text-lg font-extrabold leading-8 text-slate-900">{round.question}</p></Card><PrimaryButton onClick={next}>1차 판단하기</PrimaryButton></div>}
    {screen === 4 && <div className="space-y-4"><StepHero badge="1차 판단" title="먼저 직관적으로 판단해보세요" subtitle="정답을 찾기보다 지금 기준에서 무엇을 우선하는지 확인합니다." icon="⚖️" tone="teal"/><FirstOptionCard label="A" title={round.optionA} selected={firstChoice === "A"} onClick={() => setFirstChoice("A")} tone="blue"/><FirstOptionCard label="B" title={round.optionB} selected={firstChoice === "B"} onClick={() => setFirstChoice("B")} tone="teal"/><Card className="space-y-4 p-4"><Pill tone="gray">판단 메모</Pill><TextArea label="선택 이유" placeholder="선택 이유를 적어주세요." value={firstReason} onChange={setFirstReason} /><TextArea label="우려되는 점" placeholder="우려되는 점을 적어주세요." value={concern} onChange={setConcern} /></Card>{!canFirst && <RequiredMessage>A/B 선택, 선택 이유, 우려되는 점을 모두 입력해주세요.</RequiredMessage>}<PrimaryButton onClick={next} disabled={!canFirst}>돌발상황 확인하기</PrimaryButton></div>}
    {[5, 6, 7].includes(screen) && <div className="space-y-5"><SurpriseVisual n={screen - 4}/><Card className="p-5"><div className="mb-3 flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-orange-50 text-2xl">⚡</span><b className="text-sm text-orange-700">새롭게 고려해야 할 변수</b></div><p className="text-lg font-extrabold leading-8 text-slate-900">{round.surprises[screen - 5]}</p></Card><PrimaryButton onClick={next}>{screen === 7 ? "2차 판단으로 이동" : "다음 돌발상황"}</PrimaryButton></div>}
    {screen === 8 && <div className="space-y-4"><StepHero badge="2차 판단" title="처음 판단을 다시 조정합니다" subtitle="1차 판단과 돌발상황을 함께 놓고 방향을 다시 선택합니다." icon="🔀" tone="teal"/><Info title="나의 1차 판단 요약"><p><b>선택:</b> {firstChoice}. {firstChoiceText}</p><p><b>이유:</b> {firstReason}</p><p><b>우려:</b> {concern}</p></Info><Info title="현재 확인한 돌발상황" tone="orange"><ol className="list-decimal space-y-1 pl-5">{round.surprises.map((s, i) => <li key={i}>{s}</li>)}</ol></Info>{secondOptions.map((o) => <SecondDecisionCard key={o.value} option={o} selected={secondChoice === o.value} onClick={() => { setSecondChoice(o.value); setSecondAnswers(["", "", ""]); }} />)}{!canSecond && <RequiredMessage>기존 유지 / 일부 수정 / 판단 변경 중 하나를 선택해주세요.</RequiredMessage>}<PrimaryButton onClick={next} disabled={!canSecond}>선택별 질문으로 이동</PrimaryButton></div>}
    {screen === 9 && secondChoice && <div className="space-y-4"><StepHero badge="선택별 질문" title={`${secondChoice}의 근거를 구체화합니다`} subtitle="선택의 근거, 비용, 설명 방식을 분리해서 적어보세요." icon="📝" tone="purple"/>{selectedQuestions.map((q, i) => <Card key={q} className="space-y-3 p-4"><div className="flex items-start gap-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-violet-50 text-sm font-black text-violet-700">{i+1}</span><b className="text-sm leading-6 text-slate-800">{q}</b></div><TextArea label="답변" placeholder="구체적으로 입력해주세요." value={secondAnswers[i]} onChange={(v) => setSecondAnswers((arr) => arr.map((x, idx) => idx === i ? v : x))} /></Card>)}{!canSecondQuestions && <RequiredMessage>선택별 질문 3개에 모두 답변해야 다음으로 이동할 수 있습니다.</RequiredMessage>}<PrimaryButton onClick={next} disabled={!canSecondQuestions}>AI 프롬프트 확인하기</PrimaryButton></div>}
    {screen === 10 && <div className="space-y-5"><StepHero badge="AI 모범 프롬프트" title="프롬프트를 복사해 AI 도구에 붙여넣으세요" subtitle="내 판단과 선택별 답변이 자동으로 반영됩니다." icon="🤖" tone="purple"/><Card className="space-y-4 p-4"><pre className="max-h-72 overflow-y-auto whitespace-pre-wrap rounded-2xl bg-slate-50 p-4 text-xs leading-6 text-slate-700">{prompt}</pre><button onClick={async () => { await navigator.clipboard.writeText(prompt); setCopied(true); }} className="w-full rounded-2xl bg-violet-600 px-4 py-3 text-sm font-extrabold text-white">{copied ? "복사 완료" : "프롬프트 복사하기"}</button></Card><TextArea label="AI 답변 핵심 요약" placeholder="AI 답변의 핵심을 요약해주세요." value={aiSummary} onChange={setAiSummary} rows={5} />{!canAi && <RequiredMessage>AI 답변 핵심 요약을 입력해주세요.</RequiredMessage>}<PrimaryButton onClick={next} disabled={!canAi}>AI답변 검토하기</PrimaryButton></div>}
    {screen === 11 && <div className="space-y-4"><Pill tone="purple">AI 답변 요약</Pill><Info title="AI 답변 핵심 요약" tone="purple">{aiSummary}</Info><PrimaryButton onClick={next}>AI답변 검토하기</PrimaryButton></div>}
    {screen === 12 && <div className="space-y-4"><StepHero badge="AI답변 검토" title="AI 답변을 그대로 믿지 말고 판단해보세요" subtitle="O, X, 모르겠음으로 답변 품질을 점검합니다." icon="🔎" tone="orange"/>{reviewItems.map((q, i) => <Card key={q} className="p-4"><p className="mb-3 text-sm font-bold leading-6 text-slate-700">{q}</p><div className="grid grid-cols-3 gap-2">{(["O", "X", "모르겠음"] as ReviewChoice[]).map((a) => <button key={a} onClick={() => setReviewAnswers((arr) => arr.map((x, idx) => idx === i ? a : x))} className={`rounded-2xl border px-2 py-3 text-xs font-extrabold ${reviewAnswers[i] === a ? "border-blue-500 bg-blue-50 text-blue-700" : "border-slate-100 bg-white text-slate-500"}`}>{a}</button>)}</div></Card>)}<TextArea label="보완 메모" placeholder="X 또는 모르겠음이 있다면 보완점을 적어주세요." value={reviewNote} onChange={setReviewNote} />{!canReview && <RequiredMessage>모든 항목에 답하고 필요한 경우 보완 메모를 입력해주세요.</RequiredMessage>}<PrimaryButton onClick={next} disabled={!canReview}>최종 결정문 작성하기</PrimaryButton></div>}
    {screen === 13 && <div className="space-y-4"><StepHero badge="최종 결정" title="5줄 결정문을 완성합니다" subtitle="입력한 문장이 하나의 최종 결정문으로 이어집니다." icon="✅" tone="green"/><Info title="좋은 결정문 기준" tone="green">추상적 다짐보다 구체적 행동을 적습니다. 선택의 비용과 실행 조건이 드러나야 합니다.</Info>{finalGuides.map((g, i) => <div key={g[0]} className="space-y-2"><TextInput label={`${i + 1}. ${g[0]}`} placeholder="내용을 입력하세요" value={finalLines[i]} onChange={(v) => setFinalLines((arr) => arr.map((x, idx) => idx === i ? v : x))} /><p className="rounded-2xl bg-slate-50 px-4 py-3 text-xs leading-5 text-slate-500">{g[1]}</p></div>)}{canFinal && <Card className="border-emerald-100 bg-emerald-50 p-5"><Pill tone="green">완성 결정문 미리보기</Pill><pre className="mt-4 whitespace-pre-wrap text-sm font-semibold leading-7 text-slate-800">{finalPreview}</pre></Card>}{!canFinal && <RequiredMessage>최종 5줄 결정문을 모두 입력해야 저장할 수 있습니다.</RequiredMessage>}<PrimaryButton onClick={save} disabled={!canFinal}>제출하고 저장하기</PrimaryButton></div>}
    {screen === 14 && <div className="space-y-5"><Pill tone="green">김박사의 피드백</Pill><Card className="p-5"><pre className="whitespace-pre-wrap text-sm font-semibold leading-8 text-slate-700">{kim}</pre></Card><PrimaryButton onClick={next}>로그북 저장하기</PrimaryButton></div>}
    {screen === 15 && <div className="space-y-5"><Pill tone="green">로그북</Pill><Card className="space-y-3 p-5 text-sm"><div className="rounded-2xl bg-emerald-50 p-3 text-center text-xs font-bold text-emerald-700">브라우저 임시 저장소에 저장되었습니다.</div><div className="flex justify-between"><span>1차 판단</span><b>{firstChoice}</b></div><div className="flex justify-between"><span>2차 판단</span><b>{secondChoice}</b></div><div className="border-t pt-3 whitespace-pre-wrap">{finalPreview}</div></Card><PrimaryButton onClick={next}>전체 여정 보기</PrimaryButton></div>}
    {screen === 16 && <div className="space-y-5"><Pill>여정 요약</Pill><h2 className="text-center text-2xl font-black text-slate-900">오늘의 판단 여정이 저장되었습니다</h2><Card className="p-5"><p className="text-sm leading-7 text-slate-600">1차 판단과 돌발상황을 함께 검토했고, 선택별 질문을 통해 판단의 근거·비용·설명 방식을 구체화했습니다.</p></Card><PrimaryButton onClick={() => { reset(); setScreen(1); }}>홈으로 돌아가기</PrimaryButton></div>}
  </Shell>;
}
